"""
Django settings for Medad project.

Generated by 'django-admin startproject' using Django 5.2.2.

Documentation:
https://docs.djangoproject.com/en/5.2/topics/settings/
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# ---------------------------------------------------
# Paths
# ---------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent  # المجلد الأساسي للمشروع

# ---------------------------------------------------
# Security
# ---------------------------------------------------
SECRET_KEY = 'django-insecure-3%x=i$t_*$h)f($ekm#75gvlcyj*r0_-rpb6$6hmpy8v$%zx!i'
DEBUG = True
ALLOWED_HOSTS = [
    "medad-u5ie.onrender.com",
    "ahmed2032004.pythonanywhere.com"
]

# ---------------------------------------------------
# Installed Apps
# ---------------------------------------------------
INSTALLED_APPS = [
    'main',
    'committees',
    'control_panel',
    'takwin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# ---------------------------------------------------
# Middleware
# ---------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # لتقديم ملفات static بسرعة
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ---------------------------------------------------
# URLs & WSGI
# ---------------------------------------------------
ROOT_URLCONF = 'Medad.urls'
WSGI_APPLICATION = 'Medad.wsgi.application'

# ---------------------------------------------------
# Templates
# ---------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # يمكنك إضافة مجلد templates هنا إذا كان موجود
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ---------------------------------------------------
# Database
# ---------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ---------------------------------------------------
# Password Validation
# ---------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ---------------------------------------------------
# Internationalization
# ---------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ---------------------------------------------------
# Static Files (CSS, JS, Images)
# ---------------------------------------------------
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')  # المكان الذي تجمع فيه كل ملفات static بعد collectstatic
STATICFILES_DIRS = []  # مجلدات static إضافية أثناء التطوير (اتركه فارغ إذا لا يوجد)

# لتسريع تقديم الملفات وضغطها
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ---------------------------------------------------
# Media Files (Uploaded by Users)
# ---------------------------------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # المكان الذي تُخزن فيه الملفات المرفوعة

# ---------------------------------------------------
# Custom User Model
# ---------------------------------------------------
AUTH_USER_MODEL = 'main.CustomUser'

# ---------------------------------------------------
# Default primary key field type
# ---------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------
# Email Settings (Gmail)
# ---------------------------------------------------
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "medaad.center@gmail.com"        # بريدك
EMAIL_HOST_PASSWORD = "ukmwdflrmexnjyyt"          # App Password الذي أنشأته
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
