# Generated by Django 5.2.2 on 2025-09-11 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Takwin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aspect', models.CharField(choices=[('tarbawiu', 'تربوي'), ('shareiu', 'شرعي'), ('mhari', 'مهاري'), ('medad', 'مداد')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='takwins/')),
                ('is_done', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takwins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
