# Generated by Django 5.2.2 on 2025-09-11 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takwin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takwin',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='takwin',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='takwin',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='takwin',
            name='user',
        ),
        migrations.AlterField(
            model_name='takwin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='takwin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='takwin_images/'),
        ),
        migrations.AlterField(
            model_name='takwin',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='UserTakwin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('takwin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takwin.takwin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
