# Generated by Django 5.2.2 on 2025-09-11 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takwin', '0002_remove_takwin_created_at_remove_takwin_is_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='takwin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserTakwin',
        ),
    ]
