# Generated by Django 5.2.2 on 2025-09-12 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takwin', '0003_takwin_created_at_delete_usertakwin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTakwin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('takwin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_takwins', to='takwin.takwin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_takwins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
