# Generated by Django 5.2.2 on 2025-09-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takwin', '0004_usertakwin'),
    ]

    operations = [
        migrations.AddField(
            model_name='takwin',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
