# Generated by Django 5.2.2 on 2025-09-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takwin', '0005_takwin_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='takwin',
            options={'verbose_name': 'تكوين', 'verbose_name_plural': 'التكوين'},
        ),
        migrations.AlterField(
            model_name='takwin',
            name='aspect',
            field=models.CharField(choices=[('tarbawiu', 'تربوي'), ('shareiu', 'شرعي'), ('mhari', 'مهاري'), ('medad', 'مداد')], max_length=20, verbose_name='الجانب'),
        ),
        migrations.AlterField(
            model_name='takwin',
            name='description',
            field=models.TextField(verbose_name='وصف التكوين'),
        ),
        migrations.AlterField(
            model_name='takwin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='takwin_images/', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='takwin',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='رابط'),
        ),
        migrations.AlterField(
            model_name='takwin',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='ملف pdf'),
        ),
        migrations.AlterField(
            model_name='takwin',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان التكوين'),
        ),
    ]
