# Generated by Django 5.2.2 on 2025-09-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='coordinates',
            field=models.CharField(blank=True, help_text='أدخل الإحداثيات بهذا الشكل: 31.501, 34.466', max_length=100, null=True, verbose_name='الإحداثيات'),
        ),
    ]
