# Generated by Django 5.2.2 on 2025-09-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ads_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='details',
            field=models.CharField(default=1, help_text='وصف الاعلان', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ads',
            name='more_details',
            field=models.CharField(default=0, help_text='بإمكانك إدخال رابط هنا فقط'),
            preserve_default=False,
        ),
    ]
