# Generated by Django 5.2.2 on 2025-09-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ads_details_ads_more_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='more_details',
            field=models.CharField(blank=True, help_text='بإمكانك إدخال رابط هنا فقط'),
        ),
    ]
