# Generated by Django 5.2.2 on 2025-09-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_ads_more_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': 'إعلان', 'verbose_name_plural': 'الإعلانات'},
        ),
        migrations.RemoveField(
            model_name='ads',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='ads',
            name='loacation',
            field=models.CharField(blank=True, null=True, verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='education_level',
            field=models.CharField(blank=True, choices=[('ابتدائي', 'ابتدائي'), ('متوسط', 'متوسط'), ('ثانوي', 'ثانوي'), ('جامعي', 'جامعي')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('عضو فريق', 'عضو فريق'), ('قائد فريق', 'قائد فريق')], max_length=20, null=True),
        ),
    ]
