# Generated by Django 5.2.2 on 2025-09-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_ads_options_remove_ads_coordinates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(verbose_name='المقولة')),
            ],
            options={
                'verbose_name': 'مقولة',
                'verbose_name_plural': 'مقولات',
            },
        ),
    ]
