# Generated by Django 5.2.2 on 2025-09-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_suggestions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمين'},
        ),
    ]
