# Generated by Django 5.2.2 on 2025-09-15 12:28

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committees', models.CharField(choices=[('tarbawiu', 'تربوي'), ('shareiu', 'شرعي'), ('mhari', 'مهاري'), ('medad', 'مداد')], help_text='اختر اللجنة المناسبة', max_length=20, verbose_name='اللجنة')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='takwin_images/')),
                ('link', models.URLField(blank=True, null=True)),
                ('education_levels', multiselectfield.db.fields.MultiSelectField(choices=[('ابتدائي', 'ابتدائي'), ('متوسط', 'متوسط'), ('ثانوي', 'ثانوي'), ('جامعي', 'جامعي')], max_length=100)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='committees/')),
            ],
        ),
        migrations.CreateModel(
            name='UserCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_added', models.BooleanField(default=False)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_committees', to='committees.committee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_committees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'committee'), name='unique_user_committee')],
            },
        ),
    ]
