# Generated by Django 5.2.2 on 2025-09-17 15:29

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committee',
            options={'verbose_name': 'اللجنة', 'verbose_name_plural': 'اللجان'},
        ),
        migrations.AlterField(
            model_name='committee',
            name='committees',
            field=models.CharField(choices=[('cultural', 'الثقافية'), ('media', 'الإعلامية'), ('scientific', 'العلمية'), ('social', 'الاجتماعية'), ('sports', 'الرياضية'), ('volunteer', 'التحفيزية')], help_text='اختر اللجنة المناسبة', max_length=20, verbose_name='اللجنة'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='description',
            field=models.TextField(verbose_name='وصف البرنامج'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='education_levels',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ابتدائي', 'ابتدائي'), ('متوسط', 'متوسط'), ('ثانوي', 'ثانوي'), ('جامعي', 'جامعي')], max_length=100, verbose_name='المرحلة الإشرافية'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='takwin_images/', verbose_name='صورة'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='رابط'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='committees/', verbose_name='ملف pdf'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان البرنامج'),
        ),
    ]
