# Generated by Django 5.2.2 on 2025-09-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_alter_committee_options_alter_committee_committees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='committees_images/', verbose_name='صورة'),
        ),
    ]
